version: '3'
services:
  test-task:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    image: adjoe/golang-dev
    ports:
      - "3333:3000"
    volumes:
      - ./:/go/src/adjoe.io
    command: ["/bin/sh", "-c", "gin -t test-task/src run"]
